normal-color        = "#E8E1EF"
normal-fill-alpha   = 0.03
normal-border       = "#665577"
normal-border-width = 1
normal-border-alpha = 0.55
hover-cursor-color        = "#9CF23A"
hover-cursor-fill-alpha   = 0.10
hover-cursor-border       = "#9CF23A"
hover-cursor-border-width = 1
hover-cursor-border-alpha = 0.75
focus-color        = "#9CF23A"
focus-fill-alpha   = 0.12
focus-border       = "#9CF23A"
focus-border-width = 1
focus-border-alpha = 1.0
selected-color        = "#9CF23A"
selected-fill-alpha   = 0.18
selected-border       = "#8F4BC8"
selected-border-width = 1
selected-border-alpha = 1.0
pressed-fill-alpha   = 0.25
selection-fill-alpha = 0.38
